# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
A = np.zeros(10)
print(f"Null vector of size 10:{A} ")

Null vector of size 10:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 


3. Create a vector with values ranging from 10 to 49

In [159]:
B = np.arange(10,49)
print(f"Vector with values ranging from 10 to 49:\n\n {B} ")

Vector with values ranging from 10 to 49:

 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 


4. Find the shape of previous array in question 3

In [153]:
B.shape

(39,)

5. Print the type of the previous array in question 3

In [189]:
print(type(B))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [157]:
print("numpy version: ")
print(np.__version__)
print("\n\nnumpy configuration: ")
print(np.show_config())

numpy version: 
1.18.5


numpy configuration: 
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers

7. Print the dimension of the array in question 3


In [160]:
B.ndim

1

8. Create a boolean array with all the True values

In [161]:
arrBool=np.ones(8,dtype=bool)
arrBool

array([ True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [163]:
C = np.arange(20).reshape(4,5)
print(f"2D array:\n{C} ")

2D array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 


10. Create a three dimensional array



In [164]:
D = np.arange(27).reshape(3,3,3)
print(f"3D array\n\n:{D} ")

3D array

:[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [190]:
ini_array = np.array([1, 2, 3, 6, 4, 5]) 
print(f"Original Array:{ini_array} ")
res = ini_array[::-1] 
print(f"Reversed Array:{res} ")

Original Array:[1 2 3 6 4 5] 
Reversed Array:[5 4 6 3 2 1] 


12. Create a null vector of size 10 but the fifth value which is 1 

In [167]:
E = np.zeros(10)
print(f"Null vector of size 10:{E} ")
E[5] = 1
print(f"Updated fifth value:{E} ")

Null vector of size 10:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Updated fifth value:[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] 


13. Create a 3x3 identity matrix

In [168]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [169]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [170]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
new_arr = arr1*arr2
print(f"result: {new_arr}")

result: [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [171]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])
comparison = arr1 > arr2
print(comparison)

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [172]:
F=np.arange(0,10)
print(f"Original Array: {F}")
G = (F[F%2==1])
print(f"Result: {G}")

Original Array: [0 1 2 3 4 5 6 7 8 9]
Result: [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [173]:
print(f"Original Array: {F}")
F[F%2 == 1] = -1 
print(f"Result: {F}")

Original Array: [0 1 2 3 4 5 6 7 8 9]
Result: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [98]:
arr = np.arange(10)
np.put(arr, [5,6,7,8], 12)
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [174]:
I = x = np.ones((5,5))
I[1:-1,1:-1] = 0
print(I)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [100]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[arr2d == 5] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [101]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [175]:
arr = np.arange(0,10).reshape(2,5)
print(f"Original Array: {arr}")
new_arr1 = arr[0,0:5]
print(f"Result: {new_arr1}")


Original Array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Result: [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [176]:
print(f"Original Array: {arr}")
new_arr2 = arr[1,0:5]
new_arr2 = new_arr2[1:2]
print(f"Result: {new_arr2}")


Original Array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Result: [6]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [177]:
print(f"Original Array: {arr}")
new_arr3 = arr[0:2,2:3]
print(f"Result: {new_arr3}")


Original Array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Result: [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [178]:
from numpy import random
arr10 = random.randint(100, size=(10, 10))
print(f"min: {arr10.min()}")
print(f"max: {arr10.max()}")

min: 3
max: 98


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [179]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Intersect array: {np.intersect1d(a, b)}")

Intersect array: [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [32]:
print(np.nonzero(np.in1d(a, b))[0])

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [147]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names!='Will'])

[[ 1.14234338 -0.72491113 -0.25787076 -0.19316584]
 [-0.82876301 -0.78951738  0.35910975 -0.07492806]
 [ 0.70936845  0.91715649 -0.37618675 -0.10284418]
 [ 0.43702054  1.83790011  0.63720927  0.8583921 ]
 [-1.26867293  0.05137992 -0.12478792 -0.2195788 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [148]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
mask = (names != 'Will') | (names != 'Joe')
data = np.random.randn(7, 4)
print(data[mask])

[[-0.06446777 -1.26032558  0.81453195  0.50136051]
 [ 1.24105924 -1.62648399 -1.10493723  1.20461166]
 [-2.21884373  1.45524074 -0.96064107  0.51167021]
 [-1.58308812 -2.70744681  0.92609368 -1.56099898]
 [-0.27633969  0.63341617 -0.55992783 -0.75219179]
 [-2.04503676 -0.19183446 -0.36401039  0.35851979]
 [-0.64698528  1.68685375 -0.18283189  0.7238275 ]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
arr53 = np.arange(1,16).reshape(5,3)
arr53

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [39]:
arr224 = np.linspace(1,16,16).reshape(2,2,4)
arr224

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [40]:
arr224T = arr224.T
arr224T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [181]:
arr10 = np.arange(0.1,10)
arr10 = np.sqrt(arr10)
print(f"Sq.rt array: {arr10}\n")
arr10[arr10<0.5] = 0
print(f"Result: {arr10}")

Sq.rt array: [0.31622777 1.04880885 1.44913767 1.76068169 2.02484567 2.25831796
 2.46981781 2.66458252 2.84604989 3.01662063]

Result: [0.         1.04880885 1.44913767 1.76068169 2.02484567 2.25831796
 2.46981781 2.66458252 2.84604989 3.01662063]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [182]:
arr121 = random.randint(12, size=12)
arr122 = random.randint(12, size=12)
print(f"original first array of 12 elemets: {arr121}")
print(f"original second array of 12 elemets: {arr122}")
arr12  = np.maximum(arr121, arr122)
print(f"result: {arr12}")

original first array of 12 elemets: [ 5  7  6  0  2  2  9  5  4 10  0  4]
original second array of 12 elemets: [ 5  2  8  6  6  0  8  6  6  9 11 10]
result: [ 5  7  8  6  6  2  9  6  6 10 11 10]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [183]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
names = np.sort(names)
print(f"Unique and sorted array: {names}")

Unique and sorted array: ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [184]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
print(f"Result: {result}")

Result: [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [185]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,2]=newColumn
print(f"Result: {sampleArray}")

Result: [[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [186]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
new_arr = np.dot(x,y)
print(f"Result: {new_arr}")

Result: [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [188]:
arr20 = random.randint(20, size=20)
print(f"matrix of 20 random values: {arr20}")
print(f"Cumulative Sum: {np.cumsum(arr20)}")

matrix of 20 random values: [ 9 11 16  0  9 11  5 14  9  3 14 13  2  3 17 10  7  7 10 10]
Cumulative Sum: [  9  20  36  36  45  56  61  75  84  87 101 114 116 119 136 146 153 160
 170 180]
