# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.arange(0,10)
print(f"Original:{arr}")
arr = arr.reshape(2,5)
print(f"Result:{arr}")

Original:[0 1 2 3 4 5 6 7 8 9]
Result:[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones(10).reshape(2,5)
print(np.vstack((arr1,arr2)))

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr1 = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
arr1 = list(arr1)
arr2 = np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
arr2=list(arr2)
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
arr = np.hstack((arr1,arr2)).reshape(2,10)
arr1 = list(arr[0])
arr2 = list(arr[1])
arr = []
arr.append(arr1)
arr.append(arr2)
print(f"Result: {arr}")

Array 1: [0, 1, 2, 3, 4, 1, 1, 1, 1, 1]
Array 2: [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]
Result: [[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr =  np.arange(0,10).reshape(2,5)
print(f"Original: {arr}")
arr = arr.ravel()
print(f"Result: {arr}")


Original: [[0 1 2 3 4]
 [5 6 7 8 9]]
Result: [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr =  np.arange(0,10).reshape(2,5)
print(f"Original: {arr}")
arr = arr.ravel()
print(f"Result: {arr}")

Original: [[0 1 2 3 4]
 [5 6 7 8 9]]
Result: [0 1 2 3 4 5 6 7 8 9]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr =  np.arange(0,15)
print(f"Original: {arr}")
arr = np.reshape(arr,(5,3))
print(f"Result: {arr}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Result: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr =  np.arange(1,26).reshape(5,5)
print(f"Original: {arr}")
arr = arr**2
print(f"Result: {arr}")

Original: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Result: [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr =  np.arange(1,31).reshape(5,6)
print(f"Original: {arr}")
mean = np.mean(arr)
print(f"\nMean of array: {mean}")

Original: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Mean of array: 15.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
print(f"Original: {arr}")
std = np.std(arr)
print(f"\nStandard Deviation of array: {std}")

Original: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Standard Deviation of array: 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [10]:
print(f"Original: {arr}")
median = np.median(arr)
print(f"\nMedian of array: {median}")

Original: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Median of array: 15.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
print(f"Original: {arr}")
tran = arr.T
print(f"\nTranspose of array: {tran}")

Original: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Transpose of array: [[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr =  np.arange(1,17).reshape(4,4)
print(f"Original: {arr}")
trace = np.trace(arr) 
print(f"\nSum of diagonal elements of array: {trace}")

Original: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sum of diagonal elements of array: 34


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print(f"Original: {arr}")
det = np.linalg.det(arr)
print(f"\nDeterminant of array: {det}")

Original: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Determinant of array: -1.820448242817726e-31


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
arr =  np.arange(1,101).reshape(10,10)
print(f"Original: {arr}")
print(f"5th percentile of arr : { np.percentile(arr, 5)}")
print(f"95th percentile of arr : { np.percentile(arr, 95)}")

Original: [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
5th percentile of arr : 5.95
95th percentile of arr : 95.05


## Question:15

### How to find if a given array has any null values?

In [15]:
arr = np.array([1,2,3,4,5,6,7],dtype=float)
arr[arr%2==0]=np.NaN
print(arr)
np.isnan(arr).any()

[ 1. nan  3. nan  5. nan  7.]


True